services:
  - type: web
    name: ffc-backend
    env: node
    plan: free
    buildCommand: rm -f package-lock.json && npm install --legacy-peer-deps
    startCommand: node server.js
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: PRODUCTS_SHEET_URL
        sync: false
      - key: OFFER_SHEET_URL
        sync: false
      - key: GOOGLE_SHEET_WEBHOOK
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEET_ID
        sync: false
